eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8500

spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
