eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

# 文件存储所需参数
# 所有通过 REST APIs 上传的文件都将存储在此目录下
# 对应的类是`properties/FileProperties`
file:
  upload-dir: ./uploads

# 文件写入磁盘的阈值
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/iot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 215MB

server:
  port: 8700
