eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

server:
  port: 8302

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
