eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 下划线转换成驼峰
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 8400

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/iot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

custom:
  protocol: http
