server:
  port: 9300

spring:
  application:
    name: cloud-config-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.123.234.234:3310/db2019?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 123.123.234.234
    password:
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        min-idle: 10
        max-active: 2000
  rabbitmq:
    host: 123.123.234.234
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://123.123.234.234:7001/eureka

management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'  #凡是暴露监控、刷新的都要有actuator依赖，bus-refresh就是actuator的刷新操作
